@baseUrl = {{$dotenv BASE_URL}}

###
# @name createCredential
# @prompt user_id
# @prompt name
# @prompt callback_url
# @prompt token
# @prompt scopes[0]
POST {{baseUrl}}/v1/credentials HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "user_id": "{{user_id}}",
  "name": "{{name}}",
  "callback_url": "{{callback_url}}",
  "token": "{{token}}",
  "scopes": ["{{scopes[0]}}"]
}

###
# @name retrieveAllCredential
GET {{baseUrl}}/v1/credentials HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name retrieveCredential
# @prompt id
GET {{baseUrl}}/v1/credentials/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name updateCredential
# @prompt id
# @prompt name
# @prompt callback_url
# @prompt token
# @prompt scopes[0]
PATCH {{baseUrl}}/v1/credentials/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "callback_url": "{{callback_url}}",
  "token": "{{token}}",
  "scopes": ["{{scopes[0]}}"],
}

###
# @name deleteCredential
# @prompt id
DELETE {{baseUrl}}/v1/credentials/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json
